# Site settings
title: "A ENV 415 / A ATM 415: Climate Laboratory"
email: brose@albany.edu
description: > # this means to ignore newlines until "baseurl:"
  Class website for A ENV 415 / A ATM 415, Spring 2016
baseurl: "/facstaff/brose/classes/ENV415_Spring2016" # the subpath of your site, e.g. /blog
url: "http://www.atmos.albany.edu/facstaff/brose/classes/ENV415_Spring2016" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
